#!/bin/bash

# Harbor 安装包下载脚本
# 由于网络限制，请手动下载或使用其他方式下载

HARBOR_VERSION="v2.10.0"
HARBOR_PACKAGE="harbor-offline-installer-${HARBOR_VERSION}.tgz"
DOWNLOAD_URL="https://github.com/goharbor/harbor/releases/download/${HARBOR_VERSION}/${HARBOR_PACKAGE}"

echo "=========================================="
echo "Harbor 安装包下载说明"
echo "=========================================="
echo ""
echo "版本: ${HARBOR_VERSION}"
echo "文件: ${HARBOR_PACKAGE}"
echo "大小: ~600MB"
echo ""
echo "下载地址:"
echo "${DOWNLOAD_URL}"
echo ""
echo "=========================================="
echo "下载方式"
echo "=========================================="
echo ""

echo "方式 1: 直接下载（需要网络访问 GitHub）"
echo "----------------------------------------"
echo "curl -L -O ${DOWNLOAD_URL}"
echo ""

echo "方式 2: 使用代理下载"
echo "----------------------------------------"
echo "如果无法直接访问 GitHub，可以使用以下方式："
echo ""
echo "1. 使用镜像站点："
echo "   - 国内镜像：https://mirrors.huaweicloud.com/harbor/"
echo "   - 或搜索 'Harbor 国内镜像'"
echo ""
echo "2. 使用下载工具："
echo "   - 浏览器直接下载"
echo "   - 使用迅雷、IDM等下载工具"
echo ""

echo "方式 3: 从其他来源获取"
echo "----------------------------------------"
echo "1. 从同事或朋友处获取安装包"
echo "2. 从公司内部服务器下载"
echo "3. 从云存储服务下载"
echo ""

echo "=========================================="
echo "下载后操作"
echo "=========================================="
echo ""
echo "1. 将下载的文件放到 registry/harbor/ 目录"
echo "   ${HARBOR_PACKAGE}"
echo ""
echo "2. 解压安装包："
echo "   tar xzvf ${HARBOR_PACKAGE}"
echo ""
echo "3. 继续执行安装脚本："
echo "   ./install-harbor.sh"
echo ""

echo "=========================================="
echo "验证下载"
echo "=========================================="
echo ""
echo "下载完成后，验证文件："
echo "ls -lh registry/harbor/${HARBOR_PACKAGE}"
echo ""
echo "预期大小: ~600MB"
echo ""

echo "=========================================="
echo "需要帮助？"
echo "=========================================="
echo ""
echo "如果遇到下载问题，可以："
echo "1. 检查网络连接"
echo "2. 使用 VPN 或代理"
echo "3. 从其他渠道获取安装包"
echo "4. 联系技术支持"
echo ""

echo "=========================================="
echo "准备就绪？"
echo "=========================================="
echo ""
echo "下载完成后，运行以下命令继续："
echo "./install-harbor.sh"
echo ""